name: ipeadata-rag
services:
  redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
#    container_name: rage
    ports:
      - "8999:6379"
      - "8991:8001" #RedisInsight (optional)
    volumes:
      - redis-data-ipeadata-rag:/data

  backend:
    build:
      context: ./backend
#      dockerfile: Dockerfile.fastapi
    restart: unless-stopped
    depends_on:
      - redis
    image: ipeadata-rag/fastapi:latest
    environment:
      - REDIS_URL=redis://redis:6379
      - OLLAMA_URL=http://host.docker.internal:11434
      - API_PORT=8997
      - SENTENCE_TRANSFORMER_MODEL=all-MiniLM-L6-v2
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TIKA_SERVER_ENDPOINT=http://tika:9998/
    ports:
      - "8997:8997"
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8997/health || exit 1"]

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ipeadata-rag-ui
    volumes:
      - ./ui:/app
      - ./backend:/app/backend
    ports:
      - "8998:8998"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8991/_stcore/health || exit 1"]
    depends_on:
      - backend

  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile.mkdocs
    image: ipeadata-rag/mkdocs:latest
    container_name: ipeadata-rag-mkdocs
    ports:
      - "8996:80"
    volumes:
      - ./site:/usr/share/nginx/html

  tika:
    image: apache/tika:latest
    container_name: ipeadata-rag-tika
    ports:
      - "8995:9998"
    environment:
      - TIKA_SERVER_ENDPOINT=http://tika:9998/
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9998/ || exit 1"]

#  nginx:
#    image: nginx:latest
#    container_name: ipeadata-rag-nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - ui
#    restart: always
  
volumes:
  redis-data-ipeadata-rag:
